### ISSUE TITLE
Syntax broken with an edgy case of recursive variable expansion and quotes

### ISSUE THREAD

**Issue by felixhao28** [ptomato/sublime_autotools#5]
```bash
# Syntax good so far
$1=${$1-"${am_missing_run}$2"}
# Syntax broken
```

Found in audioseg code.

**Comment by ptomato** [comment]
Thanks for the report!

Do you have more context - is this makefile, shell, or M4 code? Could you link to the place in audioseg where it shows up?

**Comment by felixhao28** [comment]
The source can be downloaded from [It's homepage](https://gforge.inria.fr/frs/?group_id=533). The broken line is located on line 710 of `./aclocal.m4`.

**Comment by ptomato** [comment]
In this case, it's a problem with Sublime Text's shell script highlighting. The following shell script will also highlight incorrectly, even without my package:
```sh
FOO=foo
BAR=bar
FOO=${FOO-"${BAR}"}
echo "$FOO"
```
Please report a bug with Sublime Text. Feel free to CC me, if and when it gets fixed I'll make sure it works with the M4 highlighting.

**Comment by felixhao28** [comment]
Looks like a known issue https://github.com/sublimehq/Packages/issues/465
