### ISSUE TITLE
AC_CONFIG_MACRO_DIRS not highlighted

### ISSUE THREAD

**Issue by jannick0** [ptomato/sublime_autotools#6]
The macro [AC_CONFIG_MACRO_DIRS](https://www.gnu.org/software/automake/manual/html_node/Local-Macros.html) like in a `configure.ac`
~~~m4
AC_CONFIG_MACRO_DIRS([m4])
~~~
is not highlighted, when using [vscode_autotools](https://github.com/maelvalais/vscode_autotools), a fork of this repo as far as I understand.

I think this is a bug, but I am not really sure where to report it.  This here is my first shot for this.

Thanks for your great work!

**Comment by ptomato** [comment]
Thank you for the report!

Would you be interested in making a pull request to fix it? I think it should be possible to fix it by adding a `S?` to the place in [this giant regex](https://github.com/ptomato/sublime_autotools/blob/master/Autoconf.JSON-tmLanguage#L427) where the similar `AC_CONFIG_MACRO_DIR` is defined.

**Comment by jannick0** [comment]
> Would you be interested in making a pull request to fix it? I think it should be possible to fix it by adding a `S?` to the place in [this giant regex](https://github.com/ptomato/sublime_autotools/blob/master/Autoconf.JSON-tmLanguage#L427) where the similar `AC_CONFIG_MACRO_DIR` is defined.

Done - thanks for pointing me to the regexp slot for the adjustment.
